config/routes.rb
Rails.application.routes.draw do

  devise_for :managers, path: 'managers', controllers: {
    sessions: 'manager/sessions',
    registrations: 'manager/registrations'
  }

  devise_for :customers, path: 'customers', controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }

  devise_for :stores, path: 'stores', controllers: {
    sessions: 'stores/sessions',
    registrations: 'stores/registrations'
  }

  resources :managers, only: [:index, :show, :edit, :update, :destroy]
  resources :stores, only: [:index, :show]
  resources :products

  post 'duplicate', to: 'products#duplicate', as: :product_duplicate

  post '/cart', to: 'shopping_cart_item#create'
  get '/shopping_cart', to: 'shopping_cart#index'

  post '/checkout', to: 'order#create'

  get '/orders', to: 'order#index'

  put '/order_status', to: 'order#status'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :managers, dependent: :destroy
  has_many :products, dependent: :destroy
end

app/controllers/stores/confirmations_controller.rb
# frozen_string_literal: true

class Stores::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/stores/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Stores::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/stores/passwords_controller.rb
# frozen_string_literal: true

class Stores::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/stores/registrations_controller.rb
# frozen_string_literal: true

class Stores::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/stores/sessions_controller.rb
# frozen_string_literal: true

class Stores::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/stores/unlocks_controller.rb
# frozen_string_literal: true

class Stores::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_store, only: :show

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    if current_customer
      if params[:search].nil? || params[:search].empty?
        @products = Product.where(store_id: params[:id])
      else
        @products_search = Product.search do
          fulltext params[:search]
          with(:store_id, params[:id])
        end
        @products = @products_search.results
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_store
    @store = Store.find(params[:id])
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<h3 class="text-center mt-3 mb-3">Stores list</h3>

<table class="table">
  <thead>
    <tr>
      <th class="text-center" scope="col">Name</th>
      <th class="text-center" scope="col">Enter</th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td class="text-center" scope="row"><%= store.name %></td>
        <td class="text-center" scope="row"><%= link_to 'Enter', store %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<h4 class="text-center mt-3 mb-3">Store name: <%= @store.name %></h4>

<% if current_store %>

  <table class="table">
    <thead>
    <tr>
      <th class="text-center" scope="col">Name</th>
      <th class="text-center" scope="col">Username</th>
      <th colspan="3" class="text-center" scope="col">Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @store.managers.each do |manager| %>
      <tr>
        <td class="text-center" scope="row"><%= manager.name %></td>
        <td class="text-center" scope="row"><%= manager.username %></td>
        <td scope="row"><%= link_to 'Show', manager %></td>
        <td scope="row"><%= link_to 'Edit', edit_manager_path(manager) %></td>
        <td scope="row"><%= link_to 'Destroy', manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <%= link_to 'Create Manager', new_manager_registration_path, class: "btn btn-primary" %>

<% end %>

<% if current_customer %>

  <%= form_tag store_path, { :method => :get, :class => 'input-group', :type => 'search'} do %>
      <%= text_field_tag :search, params[:search], class: 'form-control' %>
      <%= submit_tag 'Search', :name => nil, class: 'btn btn-primary mb-2' %>
  <% end %>

  <table class="table">
    <thead>
    <tr>
      <th class="text-center" scope="col">Name</th>
      <th class="text-center" scope="col">Description</th>
      <th class="text-center" scope="col">Show</th>
    </tr>
    </thead>

    <tbody>
    <% @products.each do |product| %>
      <tr>
        <td class="text-center" scope="row"><%= product.name %></td>
        <td class="text-center" scope="row"><%= product.description %></td>
        <td class="text-center" scope="row"><%= link_to 'Show', product, class: "btn btn-primary" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <div class="d-flex justify-content-center">
    <%= link_to 'Back', stores_path, class: "btn btn-primary" %>
  </div>

<% end %>