config/routes.rb
Rails.application.routes.draw do

  devise_for :managers, path: 'managers', controllers: {
    sessions: 'manager/sessions',
    registrations: 'manager/registrations'
  }

  devise_for :customers, path: 'customers', controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }

  devise_for :stores, path: 'stores', controllers: {
    sessions: 'stores/sessions',
    registrations: 'stores/registrations'
  }

  resources :managers, only: [:index, :show, :edit, :update, :destroy]
  resources :stores, only: [:index, :show]
  resources :products

  post 'duplicate', to: 'products#duplicate', as: :product_duplicate

  post '/cart', to: 'shopping_cart_item#create'
  get '/shopping_cart', to: 'shopping_cart#index'

  post '/checkout', to: 'order#create'

  get '/orders', to: 'order#index'

  put '/order_status', to: 'order#status'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_one :shopping_cart
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable, :authentication_keys => [:username]

  validates :username, uniqueness: true

  has_many :orders, dependent: :destroy
  belongs_to :store, class_name: 'Store', foreign_key: :store_id, optional: true

  def email_required?
    false
  end

  def will_save_change_to_email?
    false
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :manager, optional: true
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :image
  has_many :product_variant

  accepts_nested_attributes_for :product_variant, allow_destroy: true

  belongs_to :store

  searchable do
    text :name, :description
    integer :store_id
  end
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
  belongs_to :product
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :customer
  has_many :shopping_cart_item, dependent: :destroy
end

app/models/shopping_cart_item.rb
class ShoppingCartItem < ApplicationRecord
  belongs_to :shopping_cart
end

app/models/store.rb
class Store < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :managers, dependent: :destroy
  has_many :products, dependent: :destroy
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  before_action :authenticate_manager!, except: :create
  before_action :set_order, only: :status

  def index
    @orders = Order.where(store_id: current_manager.store_id).order("created_at DESC")
  end

  def create
    @shopping_cart = current_customer.shopping_cart.delete
    @product_id = ProductVariant.find(@shopping_cart.shopping_cart_item.first.product_variant_id).product_id
    @store_id = Product.find(@product_id).store_id
    @order = Order.create(name: params[:name], phone_number: params[:phone_number],
                          address: params[:address], price: @shopping_cart.price, store_id: @store_id)
    @shopping_cart.shopping_cart_item.each do |item|
      product_variant = ProductVariant.find(item.product_variant_id)
      @order_item = OrderItem.new(cart_items: product_variant.title, items_quantity: item.quantity, order_id: @order.id)
      @order_item.save
    end
    flash[:notice] = 'Your order has been accepted'
    redirect_to root_path
  end

  def status
    if @order.status == 'new' && @order.manager_id.nil?
      @order.update_attributes(:status => 'Processing', :manager_id => current_manager.id)
      flash[:notice] = 'Order accepted'
    elsif @order.status == 'Processing' && @order.manager_id == current_manager.id
      @order.update_attribute(:status, 'Delivered')
      flash[:notice] = 'Order delivered'
    else
      flash[:notice] = 'You can\'t manage this order'
    end
    redirect_to orders_path
  end

  private

  def set_order
    @order = Order.find(params[:order_id])
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_store, only: :show

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    if current_customer
      if params[:search].nil? || params[:search].empty?
        @products = Product.where(store_id: params[:id])
      else
        @products_search = Product.search do
          fulltext params[:search]
          with(:store_id, params[:id])
        end
        @products = @products_search.results
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_store
    @store = Store.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_cart
    @shopping_cart = ShoppingCart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @shopping_cart = ShoppingCart.new(customer_id: current_customer.id)
    session[:cart_id] = @shopping_cart.id
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shopping_cart_helper.rb
module ShoppingCartHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/shared/_alerts.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>
<% elsif flash[:error] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:error] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_logged_as.html.erb
<% if current_customer %>
  Logged as: <%= current_customer.name %> (Customer)
<% elsif current_store %>
  Logged as: <%= current_store.name %> (Store)
<% elsif current_manager %>
  Logged as: <%= current_manager.name %> (Manager)
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Shoppy</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%= render 'shared/sign_in' %>
      <span class="navbar-text">
        <%= render 'shared/logged_as' %>
      </span>
        <%= render 'shared/user_actions' %>
      <li class="nav-item">
        <%= render 'shared/sign_out' %>
      </li>
    </ul>
<!--    <form class="form-inline my-2 my-lg-0">-->
<!--      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
<!--      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--    </form>-->
  </div>
</nav>

app/views/shared/_sign_in.html.erb
<% if current_customer.nil? && current_store.nil? && current_manager.nil? %>
<span class="navbar-text">Log in as:</span>
<li class="nav-item">
  <%= link_to 'Customer', new_customer_session_path, class: 'nav-link' %>
</li>
<span class="navbar-text">|</span>
<li class="nav-item">
  <%= link_to 'Store', new_store_session_path, class: 'nav-link' %>
</li>
<span class="navbar-text">|</span>
<li class="nav-item">
  <%= link_to 'Manager', new_manager_session_path, class: 'nav-link' %>
</li>
<% end %>

app/views/shared/_sign_out.html.erb
<% if current_customer %>
  <%= link_to 'Sign out', destroy_customer_session_path, method: :delete, class: 'nav-link'  %>
<% elsif current_store %>
  <%= link_to 'Sign out', destroy_store_session_path, method: :delete, class: 'nav-link'  %>
<% elsif current_manager %>
  <%= link_to 'Sign out', destroy_manager_session_path, method: :delete, class: 'nav-link'  %>
<% end %>

app/views/shared/_user_actions.html.erb
<% if current_customer %>
  <li class="nav-item">
    <%= link_to 'Stores', stores_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Cart', shopping_cart_path, class: 'nav-link' %>
  </li>
<% elsif current_store %>
  <li class="nav-item">
    <%= link_to 'Managers', managers_path, class: 'nav-link' %>
  </li>
<% elsif current_manager %>
  <li class="nav-item">
    <%= link_to 'Products', products_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Orders', orders_path, class: 'nav-link' %>
  </li>
<% end %>