config/routes.rb
Rails.application.routes.draw do

  devise_for :managers, path: 'managers', controllers: {
    sessions: 'manager/sessions',
    registrations: 'manager/registrations'
  }

  devise_for :customers, path: 'customers', controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }

  devise_for :stores, path: 'stores', controllers: {
    sessions: 'stores/sessions',
    registrations: 'stores/registrations'
  }

  resources :managers, only: [:index, :show, :edit, :update, :destroy]
  resources :stores, only: [:index, :show]
  resources :products

  post 'duplicate', to: 'products#duplicate', as: :product_duplicate

  post '/cart', to: 'shopping_cart_item#create'
  get '/shopping_cart', to: 'shopping_cart#index'

  post '/checkout', to: 'order#create'

  get '/orders', to: 'order#index'

  put '/order_status', to: 'order#status'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="display-4 text-center">Welcome to the Shoppy</h1>
  <p class="h3 text-center">Marketplace where you can buy and sell everything</p>
  <hr class="my-4">
  <p class="h4 text-center">Sign up as:</p>
  <div class="d-flex justify-content-center">
    <%= link_to 'Customer', new_customer_registration_path, class: 'btn btn-primary btn-lg align-middle', role: 'button' %>
  </div>
  <p class="h6 text-center mt-2">Or</p>
  <div class="d-flex justify-content-center">
    <%= link_to 'Store', new_store_registration_path, class: 'btn btn-primary btn-lg align-middle', role: 'button' %>
  </div>
</div>