config/routes.rb
Rails.application.routes.draw do

  devise_for :managers, path: 'managers', controllers: {
    sessions: 'manager/sessions',
    registrations: 'manager/registrations'
  }

  devise_for :customers, path: 'customers', controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }

  devise_for :stores, path: 'stores', controllers: {
    sessions: 'stores/sessions',
    registrations: 'stores/registrations'
  }

  resources :managers, only: [:index, :show, :edit, :update, :destroy]
  resources :stores, only: [:index, :show]
  resources :products

  post 'duplicate', to: 'products#duplicate', as: :product_duplicate

  post '/cart', to: 'shopping_cart_item#create'
  get '/shopping_cart', to: 'shopping_cart#index'

  post '/checkout', to: 'order#create'

  get '/orders', to: 'order#index'

  put '/order_status', to: 'order#status'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :image
  has_many :product_variant

  accepts_nested_attributes_for :product_variant, allow_destroy: true

  belongs_to :store

  searchable do
    text :name, :description
    integer :store_id
  end
end

app/models/store.rb
class Store < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :managers, dependent: :destroy
  has_many :products, dependent: :destroy
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_manager!, except: :show
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.where(store_id: current_manager.store_id)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.product_variant.build
  end

  # GET /products/1/edit
  def edit
  end

  def duplicate
    @product_dup = Product.find(params[:format]).dup
    @product_dup.save
    redirect_to products_path
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.store_id = current_manager.store.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :description, product_variant_attributes: [:id, :title, :price, :_destroy], image: [])
  end

  def check_customer

  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :image %>
      <%= form.file_field :image, multiple: true, class: "form-control" %>
    </div>

    <div class="product-variants form-group">
      <%= form.fields_for :product_variant do |var| %>
        <%= render 'product_variant_fields', f: var %>
      <% end %>
    </div>

    <div class="d-flex justify-content-center">
      <%= link_to_add_association 'Add Variant', form, :product_variant, data: {
          association_insertion_node: '.product-variants', association_insertion_method: :append }, class: 'btn btn-primary'  %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="d-flex justify-content-center">
      <div class="form-group">
        <%= form.submit 'Product', class: 'btn btn-primary' %>
      </div>
    </div>
  </form>

<% end %>

app/views/products/_product_variant_fields.erb
<fieldset class="nested-fields">
  Product variant:
  <br>
  <%= f.label :title, 'Title' %>
  <%= f.text_field :title, class: "form-control" %>
  <%= f.label :title, 'Price' %>
  <%= f.text_field :price, class: "form-control" %> <br>
  <div class="d-flex justify-content-center">
    <%= link_to_remove_association 'Remove variant', f, class: 'btn btn-primary' %>
  </div>
</fieldset>

app/views/products/edit.html.erb
<h3 class="text-center mt-3 mb-3">Edit Product</h3>

<%= render 'form', product: @product %>

<div class="d-flex justify-content-center">
  <%= link_to 'Show', @product, class: 'btn btn-primary mr-2' %>
  <%= link_to 'Back', products_path, class: 'btn btn-primary' %>
</div>

app/views/products/index.html.erb
<h3 class="text-center mt-3 mb-3">All Products</h3>

<table class="table">
  <thead>
    <tr>
      <th class="text-center" scope="col">Name</th>
      <th class="text-center" scope="col">Description</th>
      <th colspan="4" class="text-center" scope="col">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td class="text-center" scope="row"><%= product.name %></td>
        <td class="text-center" scope="row"><%= product.description %></td>
        <td scope="row"><%= link_to 'Show', product %></td>
        <td scope="row"><%= link_to 'Duplicate', product_duplicate_path(product), method: :post %></td>
        <td scope="row"><%= link_to 'Edit', edit_product_path(product) %></td>
        <td scope="row"><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="d-flex justify-content-center">
  <%= link_to 'New Product', new_product_path, class: 'btn btn-primary mt-2' %>
</div>

app/views/products/new.html.erb
<h3 class="text-center mt-3 mb-3">New Product</h3>

<%= render 'form', product: @product %>

<div class="d-flex justify-content-center">
  <%= link_to 'Back', products_path, class: 'btn btn-primary mt-2' %>
</div>

app/views/products/show.html.erb
<h4 class="text-center mt-3 mb-3">Product name: <%= @product.name %></h4>

<p>Product images:</p>

<% @product.image.each do |image| %>
  <%= image_tag image.variant(resize: '100x100') %>
<% end %>

<p class="mt-2">Product description: <%= @product.description %></p>

<% if current_customer %>
  <p>Order item:</p>
  <%= form_tag '/cart', { :method => :post, :class => 'input-group'} do %>
    <% @product.product_variant.each do |var| %>
      <label><%= var.title + ' ' + var.price.to_s %></label>
      <%= hidden_field_tag 'product_ids[]', var.id %>
      <%= number_field_tag 'product_quantities[]', 0, min: 0, class: 'input-group mb-1' %>
    <% end %>
    <%= submit_tag 'Add to Cart', class: 'btn btn-primary mt-2' %>
  <% end %>
<% end %>

<% if current_manager %>
  <div class="d-flex justify-content-center">
    <%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-primary mr-2' %>
    <%= link_to 'Back', products_path, class: 'btn btn-primary mr-2' %>
  </div>
<% elsif current_customer %>
  <div class="d-flex justify-content-center">
    <%= link_to 'Back', @product.store, class: 'btn btn-primary mt-2' %>
  </div>
<% end %>